import assert from 'node:assert/strict';
import {Workspace,KEY,parseCSV,csvExport,shelfDays,validateData,detectCarrier} from '../web/core.mjs';
import {barcodeBits,barcodeSVG} from '../web/barcode.mjs';
const memory=()=>{const map=new Map();return {getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};};
const storage=memory(),w=new Workspace(storage);
assert.equal(w.data.parcels.length,0);
const c=w.addClient({name:'Test client',email:'client@example.com'});
const a=w.addParcel({tracking:'ABC-1001',cartons:2,clientId:c});
const b=w.addParcel({tracking:'ABC-1002'});
assert.throws(()=>w.addParcel({tracking:'abc 1001'}),/already exists/);
assert.throws(()=>w.lookup('ABC-100'),/Several parcels/);
assert.equal(w.lookup('abc 1001').id,a);
assert.equal(w.lookup('%'),null);
assert.throws(()=>w.release(a,'Client'),/all expected/);
w.receive(a,{count:1,location:'Rack A',by:'Operator'});
assert.equal(w.parcel(a).receipts.length,1);
w.change(d=>{d.parcels.find(p=>p.id===a).receipts[0].at=new Date(Date.now()-12*86400000).toISOString();});
assert.equal(shelfDays(w.parcel(a)),12);
assert.throws(()=>w.updateParcel(a,{cartons:0}),/whole number/);
w.receive(a,{count:1});
assert.throws(()=>w.receive(a,{count:1}),/exceeds/);
w.release(a,'Client');
assert.throws(()=>w.undoReceipt(a),/release first/);
assert.throws(()=>w.receive(a,{count:1}),/Undo the release/);
w.undoRelease(a);w.undoReceipt(a);assert.equal(w.parcel(a).receipts.length,0);
w.addEvent(a,{status:'delivered',text:'Delivered',at:new Date().toISOString()});
w.addEvent(a,{status:'in_transit',text:'Earlier movement',at:'2020-01-01T10:00:00Z'});
assert.equal(w.parcel(a).status,'delivered');
assert.throws(()=>w.addEvent(a,{status:'customs',text:'Future',at:'2099-01-01T10:00:00Z'}),/future/);
assert.throws(()=>w.importRows([{tracking:'NEW-1'},{tracking:'NEW-2',carrier:'invalid'}]),/Invalid/);
assert.equal(w.lookup('NEW-1'),null);
assert.equal(w.importRows([{tracking:'ABC-1002'},{tracking:'NEW-3'}]),1);
const csv=parseCSV('tracking_number,description,cartons_expected\r\n"X-1","line one\nline two",2\r\n');
assert.equal(csv[0].description,'line one\nline two');assert.equal(csv[0].cartons,'2');
assert.throws(()=>parseCSV('tracking_number\n"unclosed'),/unclosed/);
w.updateParcel(b,{description:'=HYPERLINK("bad")'});
assert.ok(csvExport(w.data.parcels).includes("'=HYPERLINK"));
const backup=JSON.parse(JSON.stringify(w.data)),restored=new Workspace(memory());restored.restore(backup);
assert.deepEqual(restored.data.parcels,w.data.parcels);
const wrong=JSON.parse(JSON.stringify(backup));wrong.parcels[0].clientId='missing';assert.throws(()=>validateData(wrong),/missing client/);
const concurrent=new Workspace(storage);w.addParcel({tracking:'CONCURRENT-1'});assert.throws(()=>concurrent.addParcel({tracking:'CONCURRENT-2'}),/another tab/);
const broken=memory();broken.setItem(KEY,'broken');assert.throws(()=>new Workspace(broken),/preserved/);assert.equal(broken.getItem(KEY),'broken');
assert.ok(barcodeBits('1234567890').length<barcodeBits('ABCDEFGHIJ').length);
assert.ok(barcodeSVG('ABC-1001').includes('<rect'));
assert.throws(()=>barcodeBits('é'),/plain Latin/);
console.log('Pages core: persistence, warehouse, imports, backup, barcode and security checks passed');

assert.equal(detectCarrier('1z 999AA1 0123456784').carrier,'ups');
assert.equal(detectCarrier('GM1234567890123456').carrier,'dhlecom');
assert.equal(detectCarrier('EE123456789CN').carrier,'track17');
assert.equal(detectCarrier('1234567890').ambiguous,true);
assert.equal(detectCarrier('771234567890').ambiguous,true);
assert.equal(detectCarrier('CL123456789FR').ambiguous,true);
assert.equal(detectCarrier('not-a-tracking-number').carrier,'manual');
const auto=new Workspace(memory());
const ups=auto.addParcel({tracking:'1Z999AA10123456784'});
assert.equal(auto.parcel(ups).carrier,'ups');
assert.throws(()=>auto.addParcel({tracking:'1234567890'}),/Confirm the carrier/);
const dhl=auto.addParcel({tracking:'1234567890',carrier:'dhl'});
assert.equal(auto.parcel(dhl).carrier,'dhl');
assert.throws(()=>auto.importRows([{tracking:'GM1234567890123456'},{tracking:'771234567890'}]),/Confirm the carrier/);
assert.equal(auto.lookup('GM1234567890123456'),null);
assert.equal(auto.importRows([{tracking:'GM1234567890123456'},{tracking:'EE123456789CN'}]),2);
console.log('Carrier detection checks passed');

const {followupState,shipmentSummary}=await import('../web/core.mjs');
const checkTime=new Date(2026,9,2,12).getTime();
const fp={tracking:'TEST',carrier:'dhl',status:'in_transit',eta:'',events:[],followup:{owner:'Dom',action:'Call courier',due:'2026-10-02',checkedAt:''}};
assert.equal(followupState(fp,checkTime).priority,2);
assert.equal(followupState({...fp,eta:'2026-10-01'},checkTime).priority,3);
assert.equal(followupState({...fp,status:'exception'},checkTime).priority,4);
assert.equal(followupState({...fp,status:'delivered'},checkTime).priority,0);
assert.equal(followupState({...fp,followup:{...fp.followup,due:'',checkedAt:new Date(checkTime).toISOString()}},checkTime).priority,0);
assert.doesNotMatch(shipmentSummary(fp),/Call courier/);
console.log('Courier follow-up priority and client update checks passed');

const {matchesView,sortedShipments,deliveryMetrics,lastMovement}=await import('../web/core.mjs');
const dated={...fp,id:'dated',createdAt:new Date(checkTime-5*86400000).toISOString(),events:[{at:new Date(checkTime-4*86400000).toISOString(),status:'in_transit',source:'manual',text:'At hub'},{at:new Date(checkTime).toISOString(),source:'manual',text:'Internal notes updated'}]};
assert.equal(matchesView(dated,'quiet',checkTime),true);
assert.equal(matchesView({...dated,status:'delivered'},'quiet',checkTime),false);
assert.equal(matchesView({...dated,status:'attempt_failed'},'exceptions',checkTime),true);
assert.equal(matchesView({...dated,status:'available_for_pickup'},'delivery',checkTime),true);
assert.equal(lastMovement(dated),dated.events[0].at);
assert.equal(sortedShipments([{...dated,id:'new',createdAt:new Date(checkTime).toISOString()},dated],'oldest')[0].id,'dated');
assert.equal(deliveryMetrics([{...dated,status:'delivered',events:[{status:'delivered',at:new Date(checkTime).toISOString()}]}])[0].days,5);
const opsId=w.addParcel({tracking:'OPS-TEST',carrier:'manual'});
w.change(d=>{d.parcels.find(p=>p.id===opsId).operations={direction:'inbound',service:'Express',tags:'Urgent',localTracking:'LOCAL-TEST',localCarrier:'fedex',deliveredTo:'Recipient',podReference:'POD-TEST'};});
w.updateParcel(opsId,{description:'Edited'});
assert.equal(w.parcel(opsId).operations.localTracking,'LOCAL-TEST');
assert.match(csvExport([w.parcel(opsId)]),/final_mile_number/);
assert.match(csvExport([w.parcel(opsId)]),/POD-TEST/);
console.log('Shipment views, movement age, analytics, courier metadata and export checks passed');
