import {Workspace,KEY,STATUSES,CARRIERS,CLOSED,esc,now,parseCSV,csvExport,shelfDays,carrierURL,validateData,detectCarrier,followupState,shipmentSummary} from './core.mjs?v=2.1.0';
import {barcodeSVG} from './barcode.mjs';
const $=s=>document.querySelector(s), content=$('#content'), dialog=$('#dialog');
let workspace,route='dashboard',search='',filterStatus='',filterCarrier='',filterClient='',stockFilter='all',followFilter='attention';
let toastTimer;
const formatDate=(value,time=false)=>{if(!value)return '—';const d=new Date(value.length===10?value+'T00:00:00':value);return Number.isFinite(d.getTime())?d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric',...(time?{hour:'2-digit',minute:'2-digit'}:{})}):'—';};
const clientName=p=>workspace.data.clients.find(c=>c.id===p.clientId)?.name||'—';
const status=p=>`<span class="pill ${esc(p.status)}">${esc(STATUSES[p.status])}</span>`;
const options=(obj,chosen='',empty='')=>(empty?`<option value="">${esc(empty)}</option>`:'')+Object.entries(obj).map(([v,l])=>`<option value="${esc(v)}" ${v===chosen?'selected':''}>${esc(l)}</option>`).join('');
const clientOptions=(chosen='',empty='No client')=>`<option value="">${esc(empty)}</option>`+workspace.data.clients.map(c=>`<option value="${esc(c.id)}" ${c.id===chosen?'selected':''}>${esc(c.name)}</option>`).join('');
function toast(message,error=false){$('#toast').textContent=message;$('#toast').className='visible'+(error?' err':'');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').className='',error?7000:4000);}
function attempt(fn){try{return fn();}catch(e){toast(e.message,true);return null;}}
function go(path){location.hash=path;}
function openModal(title,body,submit){$('#dialog-title').textContent=title;$('#dialog-body').innerHTML=body;dialog.showModal();
  const form=dialog.querySelector('form');if(form&&submit)form.addEventListener('submit',e=>{e.preventDefault();const error=form.querySelector('.form-error');try{submit(Object.fromEntries(new FormData(form)));dialog.close();render();}catch(err){error.textContent=err.message;error.hidden=false;}});
  setTimeout(()=>dialog.querySelector('input,select,textarea')?.focus(),0);
}
const formEnd=(label='Save')=>`<div class="form-error error" role="alert" hidden></div><div class="actions"><button class="primary" type="submit">${esc(label)}</button><button type="button" data-close>Cancel</button></div></form>`;
function download(text,name,type='text/plain'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function backup(){download(JSON.stringify(workspace.data,null,2),`parceltrack-backup-${now().slice(0,10)}.json`,'application/json');toast('Backup downloaded');}
function exportRows(rows){download(csvExport(rows,workspace.data.clients),`parceltrack-${route}-${now().slice(0,10)}.csv`,'text/csv;charset=utf-8');toast('CSV downloaded');}
function selectedRows(){return workspace.data.parcels.filter(p=>(!search||[p.tracking,p.reference,p.description,p.notes,p.origin,p.destination,clientName(p)].join(' ').toLowerCase().includes(search.toLowerCase()))&&(!filterStatus||p.status===filterStatus)&&(!filterCarrier||p.carrier===filterCarrier)&&(!filterClient||p.clientId===filterClient));}
function warehouseRows(){return workspace.data.parcels.filter(p=>p.receipts.length && (stockFilter==='released'?!!p.release:!p.release) && (!search||[p.tracking,p.reference,p.location,clientName(p)].join(' ').toLowerCase().includes(search.toLowerCase()))&&(stockFilter!=='stale'||shelfDays(p)>=workspace.data.staleDays));}
function parcelTable(rows,warehouse=false){if(!rows.length)return `<div class="empty"><h3>${workspace.data.parcels.length?'No matching parcels':'Your workspace is ready'}</h3><p>${workspace.data.parcels.length?'Try changing the filters or add a parcel.':'Add your first parcel or import a CSV to start tracking.'}</p><button class="primary" data-action="add">Add parcel</button></div>`;
return `<div class="table-wrap"><table><thead><tr><th>Tracking / reference</th><th>Client</th>${warehouse?'<th>Location</th><th>Cartons</th><th>On shelf</th><th>Release</th>':'<th>Carrier</th><th>Status</th><th>ETA</th><th>Cartons</th>'}<th>Action</th></tr></thead><tbody>${rows.map(p=>`<tr><td><a class="tracking" href="#parcel/${encodeURIComponent(p.id)}">${esc(p.tracking)}</a><small>${esc(p.reference||p.description||'—')}</small></td><td>${esc(clientName(p))}</td>${warehouse?`<td>${esc(p.location||'—')}</td><td><span class="progress"><span class="progress-track"><span style="width:${Math.min(100,100*p.receipts.length/p.cartons)}%"></span></span>${p.receipts.length}/${p.cartons}</span></td><td class="${shelfDays(p)>=workspace.data.staleDays?'stale':''}">${shelfDays(p)} days</td><td>${p.release?esc(p.release.to):p.receipts.length===p.cartons?'Ready to release':'Partial receipt'}</td>`:`<td>${esc(CARRIERS[p.carrier])}</td><td>${status(p)}</td><td>${formatDate(p.eta)}</td><td>${p.receipts.length}/${p.cartons}</td>`}<td>${warehouse&&!p.release?`<button data-action="release" data-id="${esc(p.id)}" ${p.receipts.length!==p.cartons?'disabled':''}>Release</button>`:`<button data-action="detail" data-id="${esc(p.id)}">Open</button>`}</td></tr>`).join('')}</tbody></table></div>`;}
function overview(){const all=workspace.data.parcels,active=all.filter(p=>!CLOSED.includes(p.status)),attention=active.filter(p=>followupState(p).priority>0);
const cards=[['Active parcels',active.length,'Courier delivery pending'],['Need follow-up',attention.length,'Exceptions, delays or checks due'],['Out for delivery',active.filter(p=>p.status==='out_for_delivery').length,'Monitor delivery today'],['Delivered',all.filter(p=>p.status==='delivered').length,'Recorded in this workspace']];
content.innerHTML=`<div class="metrics">${cards.map(([label,value,note])=>`<div class="metric"><span>${label}</span><strong>${value}</strong><span>${note}</span></div>`).join('')}</div><div class="note">Carrier APIs are awaiting credentials. Open carrier tracking, record the result and schedule the next action. Checking a parcel does not automatically change its status.</div><div class="card"><div class="card-head"><h2>Today's courier follow-up</h2><a class="button" href="#followup">Open work queue</a></div>${followTable(attention.sort((a,b)=>followupState(b).priority-followupState(a).priority).slice(0,8))}</div><div class="card"><div class="card-head"><h2>Latest parcels</h2><a class="button" href="#parcels">View all</a></div>${parcelTable(all.slice(0,5))}</div>`;}
function followTable(rows){return rows.length?`<div class="table-wrap"><table><thead><tr><th>AWB / client</th><th>Reason</th><th>Next action / owner</th><th>Follow-up date</th><th>Last checked</th><th>Action</th></tr></thead><tbody>${rows.map(p=>`<tr><td><a class="tracking" href="#parcel/${encodeURIComponent(p.id)}">${esc(p.tracking)}</a><small>${esc(clientName(p))} · ${esc(CARRIERS[p.carrier])}</small></td><td>${esc(followupState(p).label)}<small>${status(p)}</small></td><td>${esc(p.followup?.action||'Check courier tracking')}<small>${esc(p.followup?.owner||'Unassigned')}</small></td><td>${formatDate(p.followup?.due)}</td><td>${formatDate(p.followup?.checkedAt,true)}</td><td><button data-action="follow" data-id="${esc(p.id)}">Follow up</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty"><h3>No parcels in this queue</h3><p>Add your courier parcels or change the filter.</p></div>';}
function followups(){const rows=selectedRows().filter(p=>!CLOSED.includes(p.status)&&(followFilter==='all'||followupState(p).priority>0)).sort((a,b)=>followupState(b).priority-followupState(a).priority);
content.innerHTML=`<div class="toolbar"><input id="search" type="search" aria-label="Search follow-up" placeholder="AWB, reference or client…" value="${esc(search)}"><select id="follow-filter" aria-label="Follow-up filter">${options({attention:'Needs attention',all:'All active parcels'},followFilter)}</select><button data-action="export-follow">Export queue</button></div><div class="card"><div class="card-head"><h2>Courier work queue <span class="count">${rows.length} parcels</span></h2></div>${followTable(rows)}</div>`;}
function followModal(id){const p=workspace.parcel(id),f=p.followup||{};openModal('Courier follow-up',`<form><p><strong>${esc(p.tracking)}</strong> · ${esc(CARRIERS[p.carrier])}</p>${carrierURL(p)?`<p><a class="button" href="${esc(carrierURL(p))}" target="_blank" rel="noopener">Open courier tracking</a></p>`:''}<div class="form-grid"><label>Assigned to<input name="owner" maxlength="120" value="${esc(f.owner)}"></label><label>Next follow-up date<input type="date" name="due" value="${esc(f.due)}"></label><label class="full">Next action<input name="action" maxlength="500" value="${esc(f.action)}" placeholder="Call DHL for clearance documents"></label><label class="full">Contact / check notes<textarea name="note" maxlength="1000" placeholder="Who was contacted, result and promised next step"></textarea></label><label class="full"><input type="checkbox" name="checked" style="width:auto"> I checked courier tracking or contacted the courier today</label></div>${formEnd('Save follow-up')}`,data=>{workspace.change(d=>{const parcel=d.parcels.find(x=>x.id===id);parcel.followup={owner:data.owner.trim(),action:data.action.trim(),due:data.due,checkedAt:data.checked?now():f.checkedAt||''};if(data.note.trim()||data.checked)parcel.events.unshift({at:now(),source:'manual',text:'Courier follow-up: '+(data.note.trim()||'Tracking checked manually')});});toast('Follow-up saved');});}
function parcels(){const rows=selectedRows();content.innerHTML=`<div class="toolbar"><input id="search" type="search" aria-label="Search parcels" placeholder="Tracking number, reference, client…" value="${esc(search)}"><select id="filter-status" aria-label="Status filter">${options(STATUSES,filterStatus,'All statuses')}</select><select id="filter-carrier" aria-label="Carrier filter">${options(CARRIERS,filterCarrier,'All carriers')}</select><select id="filter-client" aria-label="Client filter">${clientOptions(filterClient,'All clients')}</select><button data-action="import">Import</button><button data-action="export">Export CSV</button></div><div class="card"><div class="card-head"><h2>Parcels <span class="count">${rows.length} record(s)</span></h2></div>${parcelTable(rows)}</div>`;}
function warehouse(){const rows=warehouseRows();content.innerHTML=`<div class="card"><div class="card-head"><h2>Receive cartons</h2></div><div class="card-body"><form id="scan-form" class="scan-form"><label>Tracking number<input name="tracking" id="scan" required autocomplete="off" placeholder="Scan or type full tracking number"></label><label>Location<input name="location" placeholder="Rack A / Bin 2" maxlength="120"></label><label>Received by<input name="by" placeholder="Your name" maxlength="120"></label><button class="primary" type="submit">Receive 1 carton</button></form><p class="muted small">Scans add one carton at a time. Shipment status and warehouse receipt are recorded separately.</p></div></div><div class="toolbar"><input id="search" type="search" aria-label="Search warehouse" placeholder="Tracking, client or location…" value="${esc(search)}"><select id="stock-filter" aria-label="Warehouse filter">${options({all:'On shelf',stale:'Ageing stock',released:'Released'},stockFilter)}</select><button data-action="export">Export CSV</button></div><div class="card"><div class="card-head"><h2>Warehouse stock <span class="count">${rows.length} parcel(s)</span></h2><button data-action="print-stock" ${!rows.length?'disabled':''}>Print labels</button></div>${parcelTable(rows,true)}</div>`;
$('#scan-form').addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));try{const p=workspace.lookup(data.tracking);if(!p)throw new Error('Parcel not found. Add it first, then scan again.');workspace.receive(p.id,{location:data.location,by:data.by});toast(`Carton received — ${p.receipts.length+1}/${p.cartons}`);render();$('#scan').focus();}catch(err){toast(err.message,true);$('#scan').select();}});}
function clients(){content.innerHTML=`<div class="toolbar"><button class="primary" data-action="add-client">＋ Add client</button><span class="muted small">${workspace.data.clients.length} client(s)</span></div>${workspace.data.clients.length?`<div class="client-cards">${workspace.data.clients.map(c=>{const count=workspace.data.parcels.filter(p=>p.clientId===c.id).length;return `<div class="card client-card"><h3>${esc(c.name)}</h3><p>${esc(c.contact||'No contact person')}</p><p class="muted">${esc(c.email||'No email')}</p><p class="muted">${esc(c.phone||'No phone')}</p><p>${count} parcel(s)</p><div class="actions"><button data-action="client-parcels" data-id="${esc(c.id)}">View parcels</button><button data-action="edit-client" data-id="${esc(c.id)}">Edit</button></div></div>`;}).join('')}</div>`:'<div class="card empty"><h3>No clients yet</h3><p>Add a client to group their shipments and contact details.</p></div>'}<div class="note">Client records belong to this browser workspace. Shared client portals and team logins are available in the separate Python server version.</div>`;}
function settings(){content.innerHTML=`<div class="settings-grid"><div class="card"><div class="card-head"><h2>Workspace settings</h2></div><div class="card-body"><form id="settings-form"><div class="form-grid"><label class="full">Company / workspace name<input name="company" required maxlength="120" value="${esc(workspace.data.company)}"></label><label class="full">Warehouse ageing threshold (days)<input type="number" name="staleDays" min="1" max="365" required value="${workspace.data.staleDays}"></label></div><div class="actions"><button class="primary" type="submit">Save settings</button></div></form></div></div><div class="card"><div class="card-head"><h2>Backups</h2></div><div class="card-body"><p>${workspace.data.parcels.length} parcels · ${workspace.data.clients.length} clients</p><p class="muted">A JSON backup includes all clients, shipment events, receipts and releases. Use it to move your workspace to another browser.</p><div class="actions"><button class="primary" data-action="backup">Download backup</button><button data-action="restore">Restore backup</button></div><p class="muted small">Restore replaces the current workspace after confirmation.</p></div></div></div><div class="card"><div class="card-head"><h2>How this version works</h2></div><div class="card-body"><p>ParcelTrack runs directly on GitHub Pages. Records are stored in this browser on this device. Clearing site data removes them; private browsing can remove them when the session ends. Keep regular backups.</p><p>Carrier links open the carrier’s own tracking website. Status updates in this workspace are entered manually. This version does not call carrier APIs or send emails, SMS or WhatsApp alerts.</p><p>For a shared database, automatic carrier tracking and password-protected client portals, use the Python server in the <a href="https://github.com/zinx3157/parceltrack" target="_blank" rel="noopener">repository</a>.</p></div></div>`;
$('#settings-form').addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));attempt(()=>{workspace.change(d=>{d.company=data.company.trim();d.staleDays=Number(data.staleDays);if(!d.company)throw new Error('Enter a company name');});toast('Settings saved');render();});});}
function detail(id){let p;try{p=workspace.parcel(id);}catch{content.innerHTML='<div class="card empty"><h3>Parcel not found</h3><a class="button" href="#parcels">Return to parcels</a></div>';return;}
$('#title').textContent=p.tracking;const link=carrierURL(p);const facts=[['Follow-up',followupState(p).label],['Next action',p.followup?.action],['Assigned to',p.followup?.owner],['Follow-up date',formatDate(p.followup?.due)],['Last checked',formatDate(p.followup?.checkedAt,true)],['Carrier',CARRIERS[p.carrier]],['Status',STATUSES[p.status]],['Client',clientName(p)],['Reference',p.reference],['Origin',p.origin],['Destination',p.destination],['ETA',formatDate(p.eta)],['Created',formatDate(p.createdAt)],['Description',p.description],['Notes',p.notes]];
content.innerHTML=`<div class="toolbar"><a class="button" href="#parcels">All parcels</a><button class="primary" data-action="follow" data-id="${esc(id)}">Follow up</button><button data-action="copy-update" data-id="${esc(id)}">Copy client update</button><button data-action="edit" data-id="${esc(id)}">Edit details</button><button class="primary" data-action="event" data-id="${esc(id)}">Add status update</button><button data-action="print" data-id="${esc(id)}">Print carton labels</button>${link?`<a class="button" href="${esc(link)}" target="_blank" rel="noopener noreferrer">Carrier tracking</a>`:''}</div><div class="detail-grid"><div><div class="card"><div class="card-head"><h2>Shipment details</h2>${status(p)}</div><div class="card-body"><dl class="facts">${facts.map(([label,value])=>`<div><dt>${esc(label)}</dt><dd>${esc(value||'—')}</dd></div>`).join('')}</dl></div></div><div class="card"><div class="card-head"><h2>Movement & handling history</h2></div><div class="card-body"><ol class="timeline">${p.events.map(e=>`<li><span class="muted small">${formatDate(e.at,true)} · ${e.source==='warehouse'?'Warehouse':'Manual update'}</span><p>${esc(e.text)}</p></li>`).join('')}</ol></div></div></div><div><div class="card"><div class="card-head"><h2>Warehouse</h2><span class="pill">${p.receipts.length}/${p.cartons} cartons</span></div><div class="card-body"><p>${p.release?`Released to <strong>${esc(p.release.to)}</strong><br><span class="muted small">${formatDate(p.release.at,true)}</span>`:p.receipts.length===p.cartons?'Receipt complete — ready for release':p.receipts.length?'Partial receipt — awaiting remaining cartons':'Awaiting first receipt'}</p><p class="muted">Location: ${esc(p.location||'—')}</p><div class="actions">${p.release?`<button data-action="undo-release" data-id="${esc(id)}">Undo release</button>`:`<button class="primary" data-action="receive" data-id="${esc(id)}" ${p.receipts.length>=p.cartons?'disabled':''}>Receive cartons</button><button data-action="release" data-id="${esc(id)}" ${p.receipts.length!==p.cartons?'disabled':''}>Release</button>`}</div>${p.receipts.length?`<div class="receipt-list">${p.receipts.map((r,i)=>`<p>Carton ${i+1} · ${formatDate(r.at,true)}<br>${esc(r.location||'No location')} · ${esc(r.by||'No receiver name')}</p>`).join('')}</div>${!p.release?`<button class="danger" data-action="undo-receipt" data-id="${esc(id)}">Clear incorrect receipt</button>`:''}`:''}</div></div></div></div>`;}
function parcelModal(id=''){const p=id?workspace.parcel(id):{tracking:'',carrier:'auto',clientId:'',reference:'',description:'',origin:'',destination:'',eta:'',cartons:1,notes:''};
openModal(id?'Edit parcel':'Add parcel',`<form><div class="form-grid"><label>Tracking number<input name="tracking" value="${esc(p.tracking)}" maxlength="100" required ${id?'readonly':''}></label><label>Carrier<select name="carrier">${options({auto:'Auto-detect carrier',...CARRIERS},p.carrier)}</select></label><div class="full small muted" id="carrier-hint" role="status" aria-live="polite"></div><label>Client<select name="clientId">${clientOptions(p.clientId)}</select></label><label>Client reference<input name="reference" value="${esc(p.reference)}" maxlength="120"></label><label class="full">Description<input name="description" value="${esc(p.description)}" maxlength="500"></label><label>Origin<input name="origin" value="${esc(p.origin)}" maxlength="120"></label><label>Destination<input name="destination" value="${esc(p.destination)}" maxlength="120"></label><label>Expected cartons<input type="number" name="cartons" min="1" max="1000" required value="${p.cartons}"></label><label>Expected delivery date<input type="date" name="eta" value="${esc(p.eta)}"></label><label class="full">Internal notes<textarea name="notes" maxlength="1000">${esc(p.notes)}</textarea></label></div>${formEnd(id?'Save changes':'Add parcel')}`,data=>{if(id){workspace.updateParcel(id,data);toast('Parcel updated');}else{const newId=workspace.addParcel(data);go('parcel/'+newId);toast('Parcel saved');}});
const tracking=dialog.querySelector('[name=tracking]'),carrier=dialog.querySelector('[name=carrier]');
const showDetection=()=>{const detection=detectCarrier(tracking.value),hint=$('#carrier-hint');
  if(!tracking.value.trim()){hint.textContent='Carrier recognition runs as you type, paste or scan.';return;}
  if(carrier.value!=='auto'){hint.textContent=`Selected: ${CARRIERS[carrier.value]}. You can return to Auto-detect at any time.`;return;}
  if(detection.ambiguous){hint.innerHTML=`Likely matches — select the carrier to confirm: <div class="actions" style="margin-top:8px">${detection.candidates.map(c=>`<button type="button" data-carrier-choice="${c}">${esc(CARRIERS[c])}</button>`).join('')}</div>`;}
  else hint.textContent=detection.candidates.length?`Detected: ${CARRIERS[detection.carrier]} (number format). You can override this above.`:'Unrecognised format — will save as Other / Manual. You can choose a carrier above.';
};
tracking.addEventListener('input',showDetection);carrier.addEventListener('change',showDetection);$('#carrier-hint').addEventListener('click',e=>{const choice=e.target.closest('[data-carrier-choice]');if(choice){carrier.value=choice.dataset.carrierChoice;showDetection();}});showDetection();
}
function clientModal(id=''){const c=id?workspace.data.clients.find(c=>c.id===id):{};if(!c)throw new Error('Client not found');openModal(id?'Edit client':'Add client',`<form><div class="form-grid"><label class="full">Company / client name<input name="name" value="${esc(c.name)}" maxlength="120" required></label><label>Contact person<input name="contact" value="${esc(c.contact)}" maxlength="120"></label><label>Email<input type="email" name="email" value="${esc(c.email)}" maxlength="200"></label><label class="full">Phone<input type="tel" name="phone" value="${esc(c.phone)}" maxlength="100"></label><label class="full">Notes<textarea name="notes" maxlength="1000">${esc(c.notes)}</textarea></label></div>${formEnd()}`,data=>{workspace.addClient(data,id);toast('Client saved');});}
function eventModal(id){const p=workspace.parcel(id);openModal('Add manual status update',`<form><div class="form-grid"><label class="full">Shipment status<select name="status">${options(STATUSES,p.status)}</select></label><label class="full">Update<textarea name="text" required maxlength="1000" placeholder="Arrived at Toamasina — awaiting clearance"></textarea></label><label class="full">Event date / time (optional)<input type="datetime-local" name="at"></label></div>${formEnd('Save update')}`,data=>{workspace.addEvent(id,data);toast('Status update saved');});}
function receiveModal(id){const p=workspace.parcel(id);openModal('Receive cartons',`<form><p class="selected-summary">${esc(p.tracking)} · ${p.cartons-p.receipts.length} carton(s) outstanding</p><div class="form-grid"><label>Cartons arriving<input name="count" type="number" min="1" max="${p.cartons-p.receipts.length}" value="1" required></label><label>Received by<input name="by" maxlength="120" placeholder="Your name"></label><label class="full">Storage location<input name="location" maxlength="120" value="${esc(p.location)}" placeholder="Rack A / Bin 2"></label></div>${formEnd('Record receipt')}`,data=>{workspace.receive(id,data);toast('Receipt saved');});}
function releaseModal(id){const p=workspace.parcel(id);openModal('Release parcel',`<form><p>${esc(p.tracking)} · ${p.receipts.length}/${p.cartons} cartons received</p><label>Handed over to<input name="to" value="${esc(clientName(p)==='—'?'':clientName(p))}" maxlength="200" required placeholder="Recipient name / company"></label>${formEnd('Confirm release')}`,data=>{workspace.release(id,data.to);toast('Release recorded');});}
function confirmModal(title,message,fn){openModal(title,`<form><p>${esc(message)}</p>${formEnd('Confirm')}`,()=>{fn();toast('Record updated');});}
function importModal(){openModal('Import parcels',`<form><div class="note">Upload a CSV with a <strong>tracking_number</strong> column or paste one tracking number per line. Duplicate tracking numbers are skipped. Existing parcels are not overwritten. Ambiguous number formats need a carrier column or a chosen default carrier.</div><label>CSV file<input class="file-input" type="file" id="csv-file" accept=".csv,text/csv"></label><p class="small"><button type="button" data-action="template">Download CSV template</button></p><label>Or paste tracking numbers<textarea name="text" placeholder="1234567890&#10;1Z999AA10123456784"></textarea></label><div class="form-grid"><label>Default carrier<select name="carrier">${options({auto:'Auto-detect each number',...CARRIERS},'auto')}</select></label><label>Assign client<select name="clientId">${clientOptions()}</select></label></div>${formEnd('Import parcels')}`);
const form=dialog.querySelector('form');form.addEventListener('submit',async e=>{e.preventDefault();const btn=form.querySelector('button[type=submit]');btn.disabled=true;try{const data=Object.fromEntries(new FormData(form));const file=$('#csv-file').files[0];if(file?.size>5*1024*1024)throw new Error('Choose a CSV smaller than 5 MB');const rows=file?parseCSV(await file.text()):data.text.split(/\r?\n/).map(s=>s.trim()).filter(Boolean).map(tracking=>({tracking}));const added=workspace.importRows(rows.map(r=>({...r,carrier:r.carrier||data.carrier,clientId:data.clientId})));dialog.close();toast(`${added} parcels imported · ${rows.length-added} duplicates skipped`);go('parcels');render();}catch(err){const error=form.querySelector('.form-error');error.textContent=err.message;error.hidden=false;}finally{btn.disabled=false;}});}
function restoreModal(){openModal('Restore workspace',`<form><div class="note warning">Restore replaces all current records. Download a backup first if you want to keep them.</div><label>ParcelTrack JSON backup<input type="file" id="backup-file" accept=".json,application/json" required></label><label style="margin-top:18px"><input type="checkbox" name="confirm" style="width:auto" required> I understand this replaces the current workspace.</label>${formEnd('Restore backup')}`);const form=dialog.querySelector('form');form.addEventListener('submit',async e=>{e.preventDefault();try{const file=$('#backup-file').files[0];if(!file)throw new Error('Choose a backup');if(file.size>20*1024*1024)throw new Error('Choose a backup smaller than 20 MB');const data=validateData(JSON.parse(await file.text()));workspace.restore(data);dialog.close();toast('Workspace restored');render();}catch(err){const error=form.querySelector('.form-error');error.textContent=err.message;error.hidden=false;}});}
function printLabels(parcels){if(!parcels.length)throw new Error('No parcels selected');const total=parcels.reduce((sum,p)=>sum+p.cartons,0);if(total>200)throw new Error('Print at most 200 carton labels at once. Open individual parcels to print smaller batches.');
const labels=parcels.map(p=>Array.from({length:p.cartons},(_,i)=>`<section class="label"><div class="brand">${esc(workspace.data.company)}</div><div class="meta">${esc(CARRIERS[p.carrier])} · Carton ${i+1} of ${p.cartons}</div>${barcodeSVG(p.tracking)}<div class="tn">${esc(p.tracking)}</div><div class="row">${esc(clientName(p))} · ${esc(p.reference||'No reference')}</div><div class="row">${esc(p.description)}</div><div class="row">${esc(p.destination)} · ${esc(p.location||'No location')}</div></section>`).join('')).join('');
const win=window.open('','_blank');if(!win)throw new Error('Allow popups for ParcelTrack to open the print sheet');win.opener=null;win.document.write(`<!doctype html><html lang="en"><head><meta charset="utf-8"><title>ParcelTrack carton labels</title><style>body{font-family:Arial,sans-serif;margin:0;background:#e9eef2;color:#000}.bar{padding:16px;background:#15364c;color:white;position:sticky;top:0}.bar button{padding:9px 16px;cursor:pointer;font:inherit}.sheet{display:flex;flex-wrap:wrap;gap:8mm;padding:8mm}.label{box-sizing:border-box;width:100mm;height:60mm;background:white;padding:4mm;border:1px solid #111;overflow:hidden;break-inside:avoid}.brand{font-weight:bold;font-size:12pt;white-space:nowrap;overflow:hidden}.meta{font-size:8pt;margin:2mm 0}.label svg{display:block;width:92mm;height:18mm}.tn{font-family:monospace;text-align:center;font-weight:bold;font-size:11pt;margin:1mm 0}.row{font-size:8pt;margin-top:1.5mm;white-space:nowrap;overflow:hidden}@page{size:100mm 60mm;margin:0}@media print{body{background:white}.bar{display:none}.sheet{display:block;padding:0}.label{border:0;break-after:page}.label:last-child{break-after:auto}}</style></head><body><div class="bar"><button onclick="window.print()">Print ${total} carton labels</button> · 100 × 60 mm · Print at 100% scale</div><div class="sheet">${labels}</div></body></html>`);win.document.close();toast('Print sheet opened');}
function render(){if(!workspace)return;const path=location.hash.slice(1)||'dashboard';const [next,id]=path.split('/');route=['dashboard','followup','parcels','warehouse','clients','settings','parcel'].includes(next)?next:'dashboard';$('#title').textContent=({dashboard:'Courier desk',followup:'Follow-up queue',parcels:'Parcels',warehouse:'Warehouse',clients:'Clients',settings:'Data & settings',parcel:'Parcel'})[route];$('#company').textContent=workspace.data.company.toUpperCase();document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+(route==='parcel'?'parcels':route)));
if(route==='dashboard')overview();else if(route==='followup')followups();else if(route==='parcels')parcels();else if(route==='warehouse')warehouse();else if(route==='clients')clients();else if(route==='settings')settings();else detail(decodeURIComponent(id||''));
if($('#search'))$('#search').addEventListener('input',e=>{const cursor=e.target.selectionStart;search=e.target.value;render();$('#search').focus();$('#search').setSelectionRange(cursor,cursor);});
for(const [sel,set] of [['#follow-filter',v=>followFilter=v],['#filter-status',v=>filterStatus=v],['#filter-carrier',v=>filterCarrier=v],['#filter-client',v=>filterClient=v],['#stock-filter',v=>stockFilter=v]])$(sel)?.addEventListener('change',e=>{set(e.target.value);render();});}
function recovery(error){$('#add').disabled=true;content.innerHTML=`<div class="card"><div class="card-head"><h2>Workspace unavailable</h2></div><div class="card-body"><div class="error">${esc(error.message)}</div><p>Your saved records have not been overwritten. Enable browser storage or open this page in a regular browser window, then reload.</p><button id="recover">Download saved data</button></div></div>`;$('#recover').addEventListener('click',()=>{try{const raw=localStorage.getItem(KEY);if(!raw)throw new Error('No saved records found');download(raw,'parceltrack-recovery.json','application/json');}catch(err){toast(err.message,true);}});}
$('#add').addEventListener('click',()=>attempt(()=>parcelModal()));$('#close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target.hasAttribute('data-close'))dialog.close();});
document.addEventListener('click',e=>{const btn=e.target.closest('[data-action]');if(!btn||btn.disabled)return;const action=btn.dataset.action,id=btn.dataset.id;attempt(()=>{
if(action==='follow')followModal(id);else if(action==='copy-update'){navigator.clipboard.writeText(shipmentSummary(workspace.parcel(id),clientName(workspace.parcel(id)))).then(()=>toast('Client update copied')).catch(()=>toast('Clipboard unavailable. Allow clipboard access.',true));}else if(action==='export-follow')exportRows(selectedRows().filter(p=>!CLOSED.includes(p.status)&&(followFilter==='all'||followupState(p).priority>0)));else if(action==='add')parcelModal();else if(action==='detail')go('parcel/'+id);else if(action==='edit')parcelModal(id);else if(action==='event')eventModal(id);else if(action==='receive')receiveModal(id);else if(action==='release')releaseModal(id);
else if(action==='undo-release')confirmModal('Undo release','Return this parcel to warehouse stock?',()=>workspace.undoRelease(id));else if(action==='undo-receipt')confirmModal('Clear receipt','Clear all carton receipts for this parcel? The correction will remain in its history.',()=>workspace.undoReceipt(id));
else if(action==='add-client')clientModal();else if(action==='edit-client')clientModal(id);else if(action==='client-parcels'){filterClient=id;search='';filterStatus='';filterCarrier='';go('parcels');}
else if(action==='backup')backup();else if(action==='restore')restoreModal();else if(action==='import')importModal();else if(action==='export')exportRows(route==='warehouse'?warehouseRows():selectedRows());else if(action==='print')printLabels([workspace.parcel(id)]);else if(action==='print-stock')printLabels(warehouseRows());
else if(action==='template')download('tracking_number,carrier,reference,description,origin,destination,cartons_expected,eta\nEXAMPLE-001,manual,INV-001,Sample goods,Toamasina,Antananarivo,2,\n','parceltrack-import-template.csv','text/csv');});});
window.addEventListener('hashchange',()=>render());window.addEventListener('storage',e=>{if(e.key===KEY){try{workspace=new Workspace(localStorage);render();toast('Workspace refreshed from another tab');}catch(err){recovery(err);}}});
try{workspace=new Workspace(localStorage);render();}catch(error){recovery(error);}
